runtime: php83

entrypoint: serve api/index.php

handlers:
  # Página principal
  - url: /
    script: auto

  # Archivos PHP en cualquier carpeta
  - url: /(.+\.php)$
    script: auto

  # Alias público para las imágenes dentro de secciones/imagenes
  - url: /images
    static_dir: api/secciones/imagenes

  # Archivos estáticos (extra)
  - url: /(.+\.(gif|png|jpg|jpeg|css|js|ico))$
    static_files: \1
    upload: .+\.(gif|png|jpg|jpeg|css|js|ico)$